# Generated by Django 2.2.2 on 2019-06-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='programs',
            field=models.ManyToManyField(blank=True, to='programs.Program'),
        ),
    ]
