# Generated by Django 2.2.2 on 2019-07-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
            ],
        ),
    ]
