# Generated by Django 2.2.2 on 2019-06-06 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20190606_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned', to='programs.UserProfile'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier', to='programs.UserProfile'),
        ),
    ]
