export const TOGGLE_PAGE = 'TOGGLE_PAGE';
export const TOGGLE_HEADER = 'TOGGLE_HEADER';
export const TOGGLE_SIGN_ON_COURSE = 'TOGGLE_SIGN_ON_COURSE';
export const GET_PROFILE = 'GET_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';
export const ADD_PROFILE = 'ADD_PROFILE';
export const TOGGLE_LESSONS = 'TOGGLE_LESSONS';
export const TOGGLE_PROGRAMS = 'TOGGLE_PROGRAMS';